#!/usr/bin/perl -w
use strict;
use warnings;

##
# obpf - 
#
# Author: Fletcher Nichol
# $Id$
##

my $Version = "1.0.0";

use Getopt::Long;
use Pod::Usage;
use File::Basename;

# command line options
my %Options = ();


MAIN: {
	&parse_opts();
}


sub parse_opts {
	GetOptions(  \%Options, 
		"help|?", "man", "version|V", "patchurl=s" ) or pod2usage(2);

	# prints usage if --help option is specified
	pod2usage( 1 )  if ( exists $Options{help} );

	# prints a manpage if --man option is specified
	pod2usage( -verbose => 2 )  if ( exists $Options{man} );

	# if there are no files given, then exit
	pod2usage("$0: no files given." )  if ( ( @ARGV == 0 ) && ( -t STDIN) );
}


__END__


=head1 NAME

obpf - 

=head1 SYNOPSIS

B<obpf> [B<-V>] [B<--patchurl>=I<URL>] I<profile>

=head1 DESCRIPTION

B<obpf> .

=head1 OPTIONS

=over 4

=item B<--patchurl>=I<URL>

tries to download the patches from this I<URL> or from a list of I<URL>s
seperated by spaces. Any I<URL> of starting with ftp://, http:// or https://
can be used.

=item B<--version>, B<-V>

displays the version of the program

=back

=head1 SEE ALSO

perl(1)

=head1 AUTHOR

Fletcher Nichol
